version: 0.2
phases:
   install:
     runtime-versions:
         php: latest
         nodejs: 12.x
     commands:
         - apt-get update -y
         - apt-get install -y libpq-dev libzip-dev
         - apt-get install -y php-pgsql
         - curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
   pre_build:
     commands:
         - sudo apt install composer
         - sudo apt install npm
   build:
     commands:
         - npm run production
         - php artisan migrate --force
         - php artisan db:seed
artifacts:
   files:
         - '**/*'
   name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
   upload-artifacts: yes
   logs: yes
